service: cirrent-interop

custom:
  bundle:
    linting: false

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256

functions:
  app:
    handler: src/app.handler
    events:
      - httpApi:
          path: "/interop"
          method: "POST"
      - httpApi:
          path: "/"
          method: "GET"

package:
  individually: true

plugins:
  - serverless-bundle
